name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 10 * * 3"  
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    environment: casablanca   # <--- AQUÃ INDICAS EL ENVIRONMENT

    steps:
      - name: Call Supabase keep-alive
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" \
            "https://nvwucveezbnxcflnhzzi.supabase.co/rest/v1/?select=1" \
            -H "apikey: ${{ secrets.API_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}"
